inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - vendor/bundle/**/*
    - node_modules/**/*

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - Guardfile
    - config/environments/production.rb

Style/Documentation:
  Exclude:
    - 'app/controllers/*'
    - 'app/helpers/*'
    - 'app/models/*'
    - 'app/mailers/*'
    - 'config/application.rb'
