language: ruby
cache: bundler
rvm:
  - 2.4.1
install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - bin/setup
script:
  - bundle exec rake
  - bundle exec brakeman -z
  - bundle exec rubocop
