language: ruby
cache: bundler
rvm:
  - 2.4.1
before_install:
  - nvm install node
  - npm install yarn
before_script:
  - bin/setup

script:
  - bundle exec rake
  - bundle exec brakeman -z
  - bundle exec rubocop
